version: 1

update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_name: "*"
          update_type: "all"
